services:
  archbyte:
    build:
      context: ./
      target: cache
    volumes :
      - srv-archbyte:/srv/archbyte:z
    ports:
      - 8080
volumes:
  srv-archbyte:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/opt/raid/archbyte'
