services:
  archbyte:
    build:
      context: ./
      target: cache
    volumes :
      - type: bind
        source: /opt/raid/archbyte/
        target: /srv/archbyte/
    ports:
      - 8080
volumes:
  srv-archbyte:
